apiVersion: v1
kind: Service
metadata:
  name: catalougeapi
spec:
  selector:
    app: catalougeapi
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalougeapi-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: catalougeapi
  template:
    metadata: 
      labels: 
        app: catalougeapi
    spec:
      containers: 
      - name: catalouge-deployment
        image: sindahlof/catalougeapi:latest
        ports:
        - containerPort: 5000



