FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y openjdk-8-jdk wget &&

ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

RUN pip install --upgrade pip && \
    pip install pyspark

COPY utils.py /app/utils.py
COPY querryCatalouge.py /app/querryCatalouge.py

EXPOSE 7077 8080

CMD ["python3", "querryCatalouge.py"]
