FROM python:3.10-slim

RUN apt-get update && \
    apt-get install -y openjdk-17-jdk wget

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

WORKDIR /app
COPY dockerfiles/* /app/

RUN pip install --upgrade pip && pip install -r requirements.txt

EXPOSE 5000

CMD ["python3", "catalougeAPI.py"]
