/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package big.data.ingestion.data;
@org.apache.avro.specific.AvroGenerated
public enum Origin implements org.apache.avro.generic.GenericEnumSymbol<Origin> {
  USER, DATASET, SPOTIFY_TOP  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Origin\",\"namespace\":\"big.data.ingestion.data\",\"symbols\":[\"USER\",\"DATASET\",\"SPOTIFY_TOP\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
