apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ingestion-api
  labels:
    app: ingestion-api
spec:
  serviceName: ingestion-api
  replicas: 1
  selector:
    matchLabels:
      app: ingestion-api
  template:
    metadata:
      labels:
        app: ingestion-api
    spec:
      containers:
      - name: ingestion-api
        image: ofhansen/ingestion-api:latest
        ports:
        - containerPort: 8888
        resources:
          limits:
            memory: "4Gi"    # Max memory: 4GB
            cpu: "2"         # Max CPU: 2 cores
          requests:
            memory: "2Gi"    # Request memory: 2GB
            cpu: "1"         # Request CPU: 1 core
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONDONTWRITEBYTECODE
          value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: ingestion-api-service
spec:
  selector:
    app: ingestion-api
  ports:
    - protocol: TCP
      port: 8888        
      targetPort: 8888  
      nodePort: 30088   
  type: NodePort
