# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: playlist.proto
# Protobuf Python Version: 5.29.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    1,
    '',
    'playlist.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eplaylist.proto\"k\n\x04Song\x12\x11\n\ttrack_uri\x18\x01 \x01(\t\x12\x12\n\ntrack_name\x18\x02 \x01(\t\x12\x1c\n\x06\x61rtist\x18\x03 \x01(\x0b\x32\x07.ArtistH\x00\x88\x01\x01\x12\x13\n\x0b\x64uration_ms\x18\x04 \x01(\tB\t\n\x07_artist\"U\n\x06\x41rtist\x12\x13\n\x0b\x61rtist_name\x18\x01 \x01(\t\x12\x12\n\nartist_uri\x18\x02 \x01(\t\x12\x0e\n\x06genres\x18\x03 \x03(\t\x12\x12\n\npopularity\x18\x04 \x01(\x05\"\xda\x01\n\x08Playlist\x12\x14\n\x05songs\x18\x01 \x03(\x0b\x32\x05.Song\x12\x15\n\rplaylist_name\x18\x02 \x01(\t\x12\x11\n\tfollowers\x18\x03 \x01(\x05\x12\x13\n\x0bnum_artists\x18\x04 \x01(\x05\x12\x11\n\tnum_songs\x18\x05 \x01(\x05\x12\x12\n\nnum_albums\x18\x06 \x01(\x05\x12 \n\x06origin\x18\x07 \x01(\x0e\x32\x10.Playlist.Origin\"0\n\x06Origin\x12\x08\n\x04USER\x10\x00\x12\x0b\n\x07\x44\x41TASET\x10\x01\x12\x0f\n\x0bSPOTIFY_TOP\x10\x02\"#\n\rArtistRequest\x12\x12\n\nartist_uri\x18\x01 \x01(\t\"=\n\x0e\x41rtistResponse\x12\x12\n\nartist_uri\x18\x01 \x01(\t\x12\x17\n\x06\x61rtist\x18\x02 \x01(\x0b\x32\x07.Artistb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'playlist_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SONG']._serialized_start=18
  _globals['_SONG']._serialized_end=125
  _globals['_ARTIST']._serialized_start=127
  _globals['_ARTIST']._serialized_end=212
  _globals['_PLAYLIST']._serialized_start=215
  _globals['_PLAYLIST']._serialized_end=433
  _globals['_PLAYLIST_ORIGIN']._serialized_start=385
  _globals['_PLAYLIST_ORIGIN']._serialized_end=433
  _globals['_ARTISTREQUEST']._serialized_start=435
  _globals['_ARTISTREQUEST']._serialized_end=470
  _globals['_ARTISTRESPONSE']._serialized_start=472
  _globals['_ARTISTRESPONSE']._serialized_end=533
# @@protoc_insertion_point(module_scope)
